# Generated by Django 5.2.5 on 2025-08-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogpost",
            old_name="author",
            new_name="Author",
        ),
        migrations.RenameField(
            model_name="blogpost",
            old_name="blog_category",
            new_name="Blog_Category",
        ),
        migrations.RenameField(
            model_name="blogpost",
            old_name="blog_title",
            new_name="Blog_Title",
        ),
        migrations.RenameField(
            model_name="blogpost",
            old_name="content",
            new_name="Content",
        ),
        migrations.RenameField(
            model_name="blogpost",
            old_name="created_at",
            new_name="Created_at",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="Email_Address",
            field=models.EmailField(default="your@email.com", max_length=254),
        ),
    ]
